In [1]:
import numpy as np

In [13]:
a1=np.array([2,3,4,5,6])
print(a1)

[2 3 4 5 6]


In [5]:
a=np.array([2,3.4,4,5,6])
print(a)

[2.  3.4 4.  5.  6. ]


In [9]:
a.dtype

dtype('float64')

In [15]:
a1.dtype

dtype('int32')

In [17]:
b=a1.astype(float)

In [27]:
b.dtype
b.sum()
print(b.ndim)

1


In [29]:
#to change datatype we use "astype"
#to know number of dimension we use"ndim"
#to set dimensions we will use="ndmin=1,3"
#to know shape of array we use="a.shape"
#shape will be printed in the format=(1,rows,columns)


In [35]:
a=np.array([[2,3,4],[4,5,6]])
print(a.ndim)

2


In [39]:
a=np.array([2,3.4,4,5,6],ndmin=4)
print(a)

[[[[2.  3.4 4.  5.  6. ]]]]


In [43]:
a=np.array([[2,3,4],[4,5,6]])
print(a)
print(a.shape)

[[2 3 4]
 [4 5 6]]
(2, 3)


In [49]:
a=np.array([[[2,3,4],[4,5,6]]])
print(a)
print(a.shape)

[[[2 3 4]
  [4 5 6]]]
(1, 2, 3)


In [51]:
a=np.array([[[2,3,4,4,5,6]]])
print(a)
print(a.shape)

[[[2 3 4 4 5 6]]]
(1, 1, 6)


In [53]:
a=np.array([2,3,5,6])
print(a)
print(a.shape)

[2 3 5 6]
(4,)


In [69]:
a=np.array([[[2,3],[2,3],[2,3],[4,6]]])
print(a)
print(a.shape)

[[[2 3]
  [2 3]
  [2 3]
  [4 6]]]
(1, 4, 2)


In [71]:
a=np.array([[[2,3],[2,3],[2,3],[4,6]]])
print(a)
print(a.reshape(4,2))

[[[2 3]
  [2 3]
  [2 3]
  [4 6]]]
[[2 3]
 [2 3]
 [2 3]
 [4 6]]


In [73]:
a=np.array([[[2,3],[2,3],[2,3],[4,6]]])
print(a)
print(a.reshape(2,4))

[[[2 3]
  [2 3]
  [2 3]
  [4 6]]]
[[2 3 2 3]
 [2 3 4 6]]


In [75]:
a=np.array([[[2,3],[2,3],[2,3],[4,6]]])
print(a)
print(a.reshape(1,8))

[[[2 3]
  [2 3]
  [2 3]
  [4 6]]]
[[2 3 2 3 2 3 4 6]]


In [77]:
#que
not True or False and False
#(not True) or False and False
#False or (False and False)
#False or False
#False


False